### ISSUE TITLE
Syntax Error when adding to config.js (Solved)

### ISSUE THREAD

**Issue by ricardoyen** [fewieden/MMM-AlarmClock#27]
Platform (Hardware/OS):
Raspian Pi (

Node version:
V12.13
MagicMirror version:
Latest Version
Module version:
Latest Version
Description of the issue:
Im completely new to this , I add this between the calendar and compliments after the }, and before the { 

{
    module: 'MMM-AlarmClock',
    position: 'top_right',
    config: {
        alarms: [
            {time: "18:30", days: [2,4], title: "Soccer", message: "Get ready for soccer training!", sound: "alarm.mp3"},
            ...
        ],
        ...
    }
}

Then I get this error

Starting MagicMirror: v2.9.0
Loading config ...
WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:60
        ],
        ^

SyntaxError: Unexpected token ]
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:678:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: helloworld.
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Sockets connected & modules started ...
Launching application.
Shutting down server...
Stopping module helper: updatenotification
pi@raspberrypi:~/MagicMirror $ 

When I remove it, it works as per normal....

**Comment by ricardoyen** [comment]
Ok, 

I know why it didn't work !!, Finally, 

Word of advise, change your config sample to what should actually be included.... saves time...

{
			  module: 'MMM-AlarmClock',
			  position: 'top_right',
			  config: {
			    sound: 'blackforest.mp3',
			    format: 'dddd, h:mm a',
			    timer: 60000,
			    volume: 1.0,
			    touch: false,
			    fade: false,
			    alarms: [
			      {
				time: '7:00',
				days: [1,2,3,4,5,6,7],
				title: 'Morning Alarm',
				message: 'ABC!'
			      }
			    ]
			  }
		},
